/**
 * Turn the Arabic font and the Casa Cava logo into a TypeScript file.
 *
 * The font is EMBEDDED rather than loaded from the system on purpose. Arabic
 * only joins correctly if the renderer has a font that supports it, and there
 * is no guarantee about which fonts exist inside the Android WebView. Carrying
 * our own means the PDF looks identical on a phone, a laptop and a browser.
 *
 *   deno run -A tools/embed_pdf_assets.ts
 */
const here = new URL("../web/src/pdf/", import.meta.url);

function base64(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

const regular = base64(await Deno.readFile(new URL("assets/arabic-Regular.woff", here)));
const bold = base64(await Deno.readFile(new URL("assets/arabic-Bold.woff", here)));
const logo = await Deno.readTextFile(new URL("assets/logo.svg", here));

const out = `// GENERATED by tools/embed_pdf_assets.ts — do not edit by hand.
// Noto Sans Arabic UI (subset) and the Casa Cava mark, carried with the app so
// the PDF renders the same everywhere, including inside the Android WebView.

export const ARABIC_FONT_CSS = \`
@font-face {
  font-family: "CasaCava Arabic";
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url(data:font/woff;base64,${regular}) format("woff");
}
@font-face {
  font-family: "CasaCava Arabic";
  font-style: normal;
  font-weight: 700;
  font-display: block;
  src: url(data:font/woff;base64,${bold}) format("woff");
}
\`;

export const LOGO_SVG = ${JSON.stringify(logo.replace(/\n\s*/g, " ").trim())};
`;

await Deno.writeTextFile(new URL("assets.ts", here), out);
console.log(
  `web/src/pdf/assets.ts written — font ${
    Math.round((regular.length + bold.length) / 1024)
  } KB base64, logo ${Math.round(logo.length / 1024)} KB`,
);
